services:
  - type: web
    name: maestro-frontend
    env: static
    rootDir: maestro/frontend
    buildCommand: npm install && npm run build
    staticPublishPath: build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
  - type: web
    name: maestro-backend
    env: python
    rootDir: maestro/backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: maestro-db
          property: connectionString
databases:
  - name: maestro-db
    databaseName: maestro
    user: maestro
